### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by lookfirst** [mattinsler/bittrex-client#2]
The other library, https://github.com/n0mad01/node.bittrex.api/blob/master/node.bittrex.api.js, supports websockets, but no definitions for TS.

Your library support HTTP and TS, but no WS.

Why can't we have nice things? ;-)

**Comment by mattinsler** [comment]
I'm working on this too! SignalR was being ... annoying. Alternatively you could create typings for node.bittrex.api. I can't promise any timelines on adding sockets and I'd like to change over to using https://github.com/mattinsler/crypto-unit (and actually document that library). Hopefully this all comes together. I just don't have enough time. =-(

**Comment by lookfirst** [comment]
Yes, SignalR is a pile of half baked M$ crazy. Sigh. I'm running into the same issues there.

I didn't understand how CryptoUnit is better than Decimal.js or BigNumber.js https://github.com/MikeMcl/bignumber.js

I know you have some tests there, but to be honest, another number library is something I'd really shy away from implementing on my own if I can help it.

**Comment by lookfirst** [comment]
Also, how about using something like this for json typing? https://github.com/pleerock/class-transformer  Seems simpler than your current methodology.

**Comment by lookfirst** [comment]
I wrote my own. https://github.com/lookfirst/bittrex-typescript

Need to support websockets in mine too, but i'm ok with keepalive for now. closing cause this isn't important to me anymore.

**Comment by mattinsler** [comment]
Cool!

I don't like the class-transformer stuff, only because I'm a fan of POD coming back from APIs rather than classes. I like to have a clear separation of what is data and what operates on data.

**Comment by lookfirst** [comment]
Not sure I understand your reasoning, but we can just agree to disagree. =) I like statically typed code and well defined objects, otherwise I wouldn't be using TypeScript...

**Comment by mattinsler** [comment]
My client is statically typed to return interfaces of the data, so either POD or classes can fulfill this while being protected by the compiler. So we can just use objects rather than class instances and still get all the static typing goodness.

```
interface Foo {
  bar: string;
}

const foo: Foo = { bar: 5 }; // typescript will complain about this
const foo: Foo = { bar: 'hello' }; // typescript will allow this

// this also satisfies the interface, but incurs the overhead of having an extra object in the prototype chain and maintaining a class lifecycle
class FooImpl implements Foo {
  bar = 'hello';
}
```
